version: "3"

services:
  pg_bd_testeapi:
    image: postgres:latest
    container_name: pg_bd_testeapi
    environment:
      POSTGRES_DB: testeapi
      POSTGRES_USER: guilherme
      POSTGRES_PASSWORD: 123456a.
    ports:
      - "5432:5432"
    volumes:
      - /home/guilherme/dev/CRUD-API-NodejsExpress-PostgreSQ/databin/data

  pg_bd_cadastrosacolas:
    image: postgres:latest
    container_name: pg_bd_cadastrosacolas
    environment:
      POSTGRES_DB: cadastrosacolas
      POSTGRES_USER: guilherme
      POSTGRES_PASSWORD: 123456a.
    ports:
      - "5433:5432"
    volumes:
      - /home/guilherme/dev/CRUD-API-NodejsExpress-PostgreSQ/databin
